# Generated by Django 4.2.4 on 2023-08-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(to='api.student'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='students',
            field=models.ManyToManyField(to='api.student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(to='api.student'),
        ),
    ]
