# Generated by Django 4.2.4 on 2023-08-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_parent_students_alter_reward_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
