# Generated by Django 4.2.4 on 2023-08-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_school_city_alter_school_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
