# Generated by Django 4.2.4 on 2023-08-06 13:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_parent_students_alter_teacher_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='image',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='name',
        ),
        migrations.AddField(
            model_name='parent',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AddField(
            model_name='parent',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
