# Generated by Django 4.2.4 on 2023-08-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_parent_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='coin',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Coins',
        ),
    ]
