# Generated by Django 4.2.4 on 2023-08-07 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_student_coin_delete_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='school',
        ),
        migrations.AddField(
            model_name='awardgoal',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.goal'),
        ),
        migrations.AddField(
            model_name='reward',
            name='schools',
            field=models.ManyToManyField(blank=True, to='api.school'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='students',
            field=models.ManyToManyField(blank=True, to='api.student'),
        ),
    ]
