# Generated by Django 4.2.4 on 2023-08-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_reward_school_awardgoal_goal_reward_schools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reward',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
